## Repaso Numpy y Pandas

1. Crea un array de 5x2 con los valores desde 100 hasta 200 de 10 en 10

In [9]:
arr = np.arange(100,200,10)
arr = arr.reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


2. Redimensiona el array a 3x3 (se debe de eliminar el último elemento)

In [14]:
arr = arr.flat[:-1].reshape(3,3)
print(arr)

[[100 110 120]
 [130 140 150]
 [160 170 180]]


3. Crea un array con los elementos de la tercera posición de cada fila

In [15]:
arr3 = arr[:,2]
print(arr3)

[120 150 180]


4. Muestra los elementos de las filas de posición par y columna de posición impar

In [16]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i %2 == 0 or j % 2 != 0:
            print(arr[i][j])

100
110
120
140
160
170
180


5. Crea dos arrays de 2x3. Posteriormente suma los dos arrays y a su resultado eleva al cuadrado cada elemento

In [17]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
array_sum = np.add(array1, array2)
array_squared = np.square(array_sum)
print(array_squared)

[[ 64 100 144]
 [196 256 324]]


6. Crea un array de 8x3. Posteriormente dividelo en 4 subarrays

In [24]:
array83 = np.random.randint(1,10,size = (8,3))
subarrays = np.split(array83,4)
print(array83)
print(subarrays)

[[6 9 6]
 [8 9 6]
 [6 4 7]
 [3 4 8]
 [5 8 3]
 [7 6 1]
 [2 6 7]
 [8 8 5]]
[array([[6, 9, 6],
       [8, 9, 6]]), array([[6, 4, 7],
       [3, 4, 8]]), array([[5, 8, 3],
       [7, 6, 1]]), array([[2, 6, 7],
       [8, 8, 5]])]


7. Dado un array de 3x3. Crea un nuevo array con este ordenado por la 2ª fila y otro array con este array ordenado por la 2ª columna

In [25]:
# Creamos el array de ejemplo
arr = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Array original:")
print(arr)

# Ordenar por la 2ª fila
sorted_by_row = arr[:, arr[1, :].argsort()]
print("Array ordenado por la 2ª fila:")
print(sorted_by_row)

# Ordenar por la 2ª columna
sorted_by_col = arr[arr[:, 1].argsort()]
print("Array ordenado por la 2ª columna:")
print(sorted_by_col)

Array original:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Array ordenado por la 2ª fila:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Array ordenado por la 2ª columna:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


8. Dado un array de 3x3. Devuelve sus mínimos de cada columna y el máximo de cada fila

In [26]:
arr = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Array original:")
print(arr)

min_by_col = np.min(arr, axis=0)
print("Mínimo de cada columna:")
print(min_by_col)

max_by_row = np.max(arr, axis=1)
print("Máximo de cada fila:")
print(max_by_row)

Array original:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Mínimo de cada columna:
[3 2 1]
Máximo de cada fila:
[9 6 3]


9. Dado un array de 3x3 elimina su 2ª columna y añadela al inicio

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array original:")
print(arr)

col_to_move = arr[:, 1]
arr = np.delete(arr, 1, axis=1)
arr = np.insert(arr, 0, col_to_move, axis=1)

print("Array con la 2ª columna al principio:")
print(arr)


Array original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array con la 2ª columna al principio:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


10. Crea un DataFrame con la información de *coches.csv*

In [36]:
import pandas as pd
import numpy as np
coches = pd.read_csv("coches.csv")
coches = coches.set_index('index')
coches.head()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

11. Muestra la compañía que tenga el coche más caro

In [32]:
print(coches[coches.price == coches.price.max()]['company'])

index
47    mercedes-benz
Name: company, dtype: object


12. Muestra todos los coches de Toyota

In [37]:
coches[coches.company == 'toyota']

company body-style  wheel-base  length engine-type num-of-cylinders   
index                                                                       
66     toyota  hatchback        95.7   158.7         ohc             four  \
67     toyota  hatchback        95.7   158.7         ohc             four   
68     toyota  hatchback        95.7   158.7         ohc             four   
69     toyota      wagon        95.7   169.7         ohc             four   
70     toyota      wagon        95.7   169.7         ohc             four   
71     toyota      wagon        95.7   169.7         ohc             four   
79     toyota      wagon       104.5   187.8        dohc              six   

       horsepower  average-mileage    price  
index                                        
66             62               35   5348.0  
67             62               31   6338.0  
68             62               31   6488.0  
69             62               31   6918.0  
70             62               27   7898.0  
71             62               27   8778.0  
79            156               19  15750.0

13. Muestra cuántos coches tiene cada compañía

In [39]:
coches.company.value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

14. Muestra todas las compañías con su precio más caro

In [41]:
coches.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

15. Calcula la media de kilometros de cada compañía

In [48]:
coches.groupby('company')['average-mileage'].mean().apply(lambda x: int(x) * 1.6)

company
alfa-romero      32.0
audi             32.0
bmw              30.4
chevrolet        65.6
dodge            49.6
honda            41.6
isuzu            52.8
jaguar           22.4
mazda            44.8
mercedes-benz    28.8
mitsubishi       46.4
nissan           49.6
porsche          27.2
toyota           44.8
volkswagen       49.6
volvo            36.8
Name: average-mileage, dtype: float64

16. Ordena los coches por precio

In [50]:
coches.sort_values('price')

company body-style  wheel-base  length engine-type   
index                                                             
16         chevrolet  hatchback        88.4   141.1           l  \
36             mazda  hatchback        93.1   159.1         ohc   
66            toyota  hatchback        95.7   158.7         ohc   
49        mitsubishi  hatchback        93.7   157.3         ohc   
37             mazda  hatchback        93.1   159.1         ohc   
...              ...        ...         ...     ...         ...   
14               bmw      sedan       103.5   193.8         ohc   
47     mercedes-benz    hardtop       112.0   199.2        ohcv   
31             isuzu      sedan        94.5   155.9         ohc   
32             isuzu      sedan        94.5   155.9         ohc   
63           porsche  hatchback        98.4   175.7       dohcv   

      num-of-cylinders  horsepower  average-mileage    price  
index                                                         
16               three          48               47   5151.0  
36                four          68               30   5195.0  
66                four          62               35   5348.0  
49                four          68               37   5389.0  
37                four          68               31   6095.0  
...                ...         ...              ...      ...  
14                 six         182               16  41315.0  
47               eight         184               14  45400.0  
31                four          70               38      NaN  
32                four          70               38      NaN  
63               eight         288               17      NaN  

[61 rows x 9 columns]